FROM busybox:latest 

#FROM uhub.service.ucloud.cn/dujingyu_jenkins/hello:v1.0
    
MAINTAINER <edward.yang@ucloud.cn>
    
COPY  a.log /  
RUN echo '易有料测试1' > /tmp/test.txt    
#CMD ["/hello"]
CMD ["top"]
