apiVersion: v1
kind: Pod
metadata:
  name: hello 
spec:
  containers:
  - name: hello
    image: uhub.service.ucloud.cn/dujingyu_jenkins/hello:v1.0  
    command:
      - /hello 
  restartPolicy: Never 
